create table if not exists public.cine_subtitles (
  id bigint generated by default as identity primary key,
  unique_key text not null unique,
  tmdb_id bigint,
  title text not null,
  normalized_title text not null,
  year integer,
  season integer,
  episode integer,
  language text not null default 'Sinhala',
  format text not null default 'SRT',
  telegram_channel_id text not null,
  telegram_message_id bigint not null,
  telegram_file_id text not null,
  telegram_file_unique_id text,
  file_name text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists cine_subtitles_lookup_idx on public.cine_subtitles (tmdb_id,year,season,episode,language);
create index if not exists cine_subtitles_title_idx on public.cine_subtitles (normalized_title);

create table if not exists public.cine_subtitle_notifications (
  id bigint generated by default as identity primary key,
  unique_key text not null unique,
  user_id text not null,
  tmdb_id bigint,
  title text not null,
  year integer,
  season integer,
  episode integer,
  language text not null default 'Sinhala',
  notified boolean not null default false,
  created_at timestamptz not null default now(),
  notified_at timestamptz
);
create index if not exists cine_subtitle_notifications_lookup_idx on public.cine_subtitle_notifications (tmdb_id,season,episode,language,notified);
